version: '3.0'

services:
  postgres:
    container_name: postgres
    build:
      dockerfile: Dockerfile-db
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_INNER_PORT}
    networks:
      - nestjs-network

  main:
    container_name: main
    build:
      context: .
      dockerfile: Dockerfile-app
    env_file:
      .env
    volumes:
      - .:/app
      - /app/node_modules

    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    restart: always

    networks:
      - nestjs-network

volumes:
  pgdata:

networks:
  nestjs-network:
    driver: bridge