version: '3.0'
services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      .env
    volumes:
      - .:/app
      - /app/node_modules

    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: postgres
    image: postgres:16
    env_file:
      .env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${PGPORT}:${PGPORT}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: