FROM postgres:16

  # Set environment variables for the PostgreSQL database
#ENV POSTGRES_DB=mydatabase
#ENV POSTGRES_USER=myuser
#ENV POSTGRES_PASSWORD=mypassword

  # Copy initialization scripts to Docker container
#COPY init.sql /docker-entrypoint-initdb.d/

  # Expose the PostgreSQL port
#EXPOSE 5432