version: '3.0'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile-app
    env_file:
      .env
    volumes:
      - .:/app
      - /app/node_modules

    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always
    networks:
      - app_bridge

  db_postgres:
    container_name: db_postgres
    build:
      dockerfile: Dockerfile-pg
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}
    networks:
      - app_bridge

volumes:
  pgdata:

networks:
  app_bridge: