version: '3.0'

services:
  postgres:
    container_name: postgres
    build:
      dockerfile: Dockerfile-db
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile-app
    env_file:
      .env
    volumes:
      - .:/app
      - /app/node_modules

    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always

volumes:
  pgdata: